name = "import-artist-worker"
main = "./index.js"
compatibility_date = "2023-01-01"

account_id = "${CF_ACCOUNT_ID}"
workers_dev = true

[observability]
enabled = true

[env.production]
name = "import-artist-worker-production"
routes = [
  { pattern = "coryd.dev/api/import-artist*", zone_id = "${CF_ZONE_ID}" }
]
