name = "scheduled-rebuild-worker"
main = "./index.js"
compatibility_date = "2023-01-01"

account_id = "${CF_ACCOUNT_ID}"
workers_dev = true

[env.production]
name = "scheduled-rebuild-worker-production"
triggers = {crons = ["0 * * * *"]}