name = "analytics-worker"
main = "./index.js"
compatibility_date = "2023-01-01"

account_id = "${CF_ACCOUNT_ID}"
workers_dev = true

[env.production]
name = "analytics-worker-production"
routes = [
  { pattern = "coryd.dev/js/*", zone_id = "${CF_ZONE_ID}" },
  { pattern = "coryd.dev/api/event", zone_id = "${CF_ZONE_ID}" }
]