name = "sitemap-worker"
main = "./index.js"
compatibility_date = "2023-01-01"

account_id = "${CF_ACCOUNT_ID}"
workers_dev = true

[env.production]
name = "sitemap-worker-production"
routes = [
  { pattern = "coryd.dev/sitemap.xml", zone_id = "${CF_ZONE_ID}" },
]