name = "contact-form-worker"
main = "./index.js"
compatibility_date = "2023-01-01"

account_id = "${CF_ACCOUNT_ID}"
workers_dev = true

[env.production]
name = "contact-form-worker-production"
routes = [
  { pattern = "coryd.dev/api/contact", zone_id = "${CF_ZONE_ID}" }
]